# Generated by Django 5.2.6 on 2025-12-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rollno', models.IntegerField()),
                ('subject', models.CharField(max_length=40)),
                ('mark', models.CharField(max_length=40)),
            ],
        ),
    ]
