# Generated by Django 5.2.6 on 2025-12-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('Dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collage_management_Sys_App.departmentmodel')),
            ],
        ),
    ]
